name: Deploy Site
on:
  push:
    branches:
      - feature/rene/pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
      - run: dotnet run -- deploy
        working-directory: ./StatiqWebTest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
